### ISSUE TITLE
Unknown Light Version

### ISSUE THREAD

**Issue by Lew7878** [Lethegrin/HomebridgeMagicHome-DynamicPlatform#1]
Hi,

I have three of these RGB LED Strip controllers: [link](https://www.amazon.co.uk/SODIAL-Controller-Compatible-Activated-Function/dp/B07HF3GPJY/ref=asc_df_B07HF3GPJY/?tag=googshopuk-21&linkCode=df0&hvadid=394317030617&hvpos=&hvnetw=g&hvrand=11553860419662734901&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9046466&hvtargid=pla-611081076668&psc=1&tag=&ref=&adgrpid=80755971054&hvpone=&hvptwo=&hvadid=394317030617&hvpos=&hvnetw=g&hvrand=11553860419662734901&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9046466&hvtargid=pla-611081076668)

They appear in HomeKit and can be turned on and off, but any change to their brightness or color gives no response and causes an Unknown Light Version message in the log.
[log.txt](https://github.com/Lethegrin/HomebridgeMagicHome-DynamicPlatform/files/4684699/homebridge.log.txt)

**Comment by Lethegrin** [comment]
I was waiting for someone with this version of the controller. I will add that functionality and get back to you. Thank you for posting your log, it's exactly what I needed.

**Comment by Lethegrin** [comment]
try updating now
`npm install -g homebridge-magichome-dynamic-platform`

**Comment by Lethegrin** [comment]
Actually scratch that, wait one moment, need a little more logic. I don't have the RGB controller here so I can't test it.

**Comment by Lethegrin** [comment]
Alright give it a shot.

**Comment by Lew7878** [comment]
I have updated, I'm getting no unknown device errors but I can still only turn the strips on and off. Dimming and colour change have no effect on the lights. 

This could just be an issue on my end, I'm struggling to get any plugin working with these strips, although yours is the closest I have gotten, so thank you!

**Comment by Lethegrin** [comment]
Yeah dimming won’t work if color change won’t work, the controllers dim by changing the brightness of each color. 

I’m sure you’ve got them changing color with the magichome app?

Open the magic home app and click settings. 

Magichome original app: gear icon in the top left corner. 

Magichome “pro” app: gear icon in the top left corner>device settings

Your device should show with a name and version. Something like:
Bulb A8095B 
ABCD12345 , v6

What does yours show?

I can work together with you directly on the Homebridge discord group here: https://discord.gg/eeZGpj

I’m sure it’s just expecting a certain protocol that we need to figure out. Which we will. Contact me.

**Comment by Lew7878** [comment]
All three of my controllers appear as v4. I’ve posted the issue on the discord under magichome. thank you for your help!

**Comment by Lethegrin** [comment]
I have updated the plugin. Please update by following instructions left at the discord magichome channel.

**Comment by Lethegrin** [comment]
Issue was solved by determining RGB controller’s protocol and adding logic for it.
