### ISSUE TITLE
Warm White issue

### ISSUE THREAD

**Issue by kevinjohncutler** [Lethegrin/HomebridgeMagicHome-DynamicPlatform#2]
First of all, this is working almost perfectly, thanks so much! It looks like my particular bulbs respond to HomeKit commands perfectly for color and brightness, but toggling to white sends it to a 'cool white' instead of the 'warm white' that Magic Home sets it to. I tried editing the preset, switching to warm in Magic Home, and then saving the preset, but that didn't work (that _does_ work nicely for any RGB setting).

**Comment by Lethegrin** [comment]
Hey, first of all thank you. It's good to hear that it's working _almost_ perfectly. May I please see your log.txt and a link to the exact bulbs you bought?

How exactly are you toggling to white? I'm afraid I haven't explained that functionality yet in the readme. Once you get close to the center of the RGB reticle, the bulbs turn white. The left side controls the cool white brightness, the right side controls the warm white brightness. That is, if you have both white types.

Alternatively you can simply say "hey siri, set the bulbs to warm/cool white"

Do your bulbs have a dedicated "cool white" and "warm white" LED (RGBWW) or just "warm white" (RGBW).

We'll get this working. Don't worry.

**Comment by kevinjohncutler** [comment]
Here is the [link](https://smile.amazon.com/gp/product/B07FMPSH1Y/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) for the bulbs. They do have both dedicated white types built in, though annoyingly they default to the cool white (that could be the cause of the issue). I am successfully toggling to warm white through the Magic Home iOS app. And wow! Asking Siri to set them **warm** white does work, but asking for just 'white' sets them to cool white. This is the same behavior as I have with Alexa voice commands, again due to the fact that they default to the cool white. 

Here is a fresh log after restarting Homebridge:
[5/27/2020, 21:09:31] Loaded config.json with 0 accessories and 1 platforms.
[5/27/2020, 21:09:31] ---
[5/27/2020, 21:09:32] Loaded plugin: homebridge-config-ui-x@4.21.0
[5/27/2020, 21:09:32] Registering platform 'homebridge-config-ui-x.config'
[5/27/2020, 21:09:32] ---
[5/27/2020, 21:09:32] Loaded plugin: homebridge-magichome-dynamic-platform@1.1.3
[5/27/2020, 21:09:32] Registering platform 'homebridge-magichome-dynamic-platform.homebridge-magichome-dynamic-platform'
[5/27/2020, 21:09:32] ---
[5/27/2020, 21:09:32] Loading 1 platforms...
[5/27/2020, 21:09:32] [homebridge-magichome-dynamic-platform] Initializing homebridge-magichome-dynamic-platform platform...
[5/27/2020, 21:09:32] [homebridge-magichome-dynamic-platform] Loading accessory from cache... 8
[5/27/2020, 21:09:32] [homebridge-magichome-dynamic-platform] Loading accessory from cache... 8
[5/27/2020, 21:09:32] [homebridge-magichome-dynamic-platform] Loading accessory from cache... 8
[5/27/2020, 21:09:32] [homebridge-magichome-dynamic-platform] Loading accessory from cache... 8
Setup Payload:
X-HM://0023ISYWY4CM6

**Comment by Lethegrin** [comment]
In your homebridge html page please go to settings (3 vertical dots) >UI Settings>Click on "Advanced" > make sure "Enable / disable debug level logging" is checked, then restart homebridge, then send me your log after changing from red to white back once or twice using your voice.

Then drag and drop your homebridge.log as a file here.

I just tried telling siri to "set my lights to white" and it gave the same order as if I said "set my lights to warm white". I find it odd that it would do something different on your end. I do not interface with the magichome app. Instead I message the lights directly in the same manor that the magic-home does. 

There should be no default color as my plugin is listening for Siri to give me a specific Hue and Saturation value "white, warmwhite, or cool white". Let's see what the logs say.

While you're at it, in addition, in the homekit rgb control screen (not temperature control) drag your finger accross the equator of the circle. It should go from teal>cool white>both whites> warm white> red. Let me know if this is or isn't the case.

**Comment by kevinjohncutler** [comment]
I'll need to figure out how to get homebridge to write the logs to homebridge.log tomorrow (lots of leads from google, but need to sleep first haha). In the meantime, I have discovered (by doing the obvious thing and looking at the actual LED array) that these bulbs have dedicated warm white LEDs, but the cool white seems to use the same RGB modules as any of the color settings. That would be why, when going across the color wheel via homekit, warm white is never activated - only the cool white.

**Comment by kevinjohncutler** [comment]
[homebridge.log](https://github.com/Lethegrin/HomebridgeMagicHome-DynamicPlatform/files/4698111/homebridge.log)
Attached is the log file - I cleared it out and restarted the service, then toggled the lights. The last three commands I made were to set the lights red, then warm white, then white (all by Siri), which sets them correctly as red, then correctly as warm white, then as a cool white (which is not its own designated set of LEDS as mentioned above).

**Comment by Lethegrin** [comment]
Thank you for the log. It has shed light on the issue although I cannot duplicate it on my end. I will investigate the code.


```
[39m Current HSL and Brightness: h:0 s:0 l:50 br:100
[39m Setting colors without white: r:127 g:127 b:127

```

Here shows the exact bug you were describing. saturation "s:0" is set to 0. The code is supposed to translate this as warm white. In fact. Anything less than 10 saturation (depending on your config) is supposed to set colors rgb to 0,0,0 and warmwhite whatever brightness you're set at.

My temporary solution to you is to continue saying "warm white" when directing Siri. Additionally go to your config file and temporarily change `"colorWhiteThreshold": 10,` to something extreme like `"colorWhiteThreshold": 50,` save and restart. Then try moving the reticle to the center of the color wheel. Let me know the results.

I will get back to you about this bug and let you know when to update the plugin. Thanks again.

**Comment by Lethegrin** [comment]
Okay, I have added a new case to check for saturation and hue both at 0. Please update the plugin, restart homebridge. Let me know how it goes.

`npm install -g homebridge-magichome-dynamic-platform`

**Comment by kevinjohncutler** [comment]
The recent update you made works perfectly! I didn't have to make a single change, my existing config and scenes now work flawlessly. Thanks so much!

**Comment by Lethegrin** [comment]
Happy to be of service. Enjoy.

**Comment by Lethegrin** [comment]
Issue was solved by adding a check if hue and saturation were both set to 0. Perhaps caused by the hue function being called before saturation had a chance to truely be set to 0.

**Comment by Lethegrin** [comment]
Issue was solved by adding a check if hue and saturation were both set to 0. Perhaps caused by the hue function being called before saturation had a chance to truely be set to 0.
